version: "3.2"
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    user: root
    ports:
      - "3316:3306"
    environment:
      # MYSQL_ROOT_PASSWORD: ${PASSWORD_DATABASE_ROOT}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      TZ: America/Manaus
    env_file:
      - .env
    volumes:
      - "./mysqldata:/var/lib/mysql"
      - "./mysqlconfig:/etc/mysql/conf.d"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
